version: '3.8'
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
      - ./init:/docker-entrypoint-initdb.d
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
volumes:
  mongo_data: