logging:
  level:
    org:
      springframework.security: DEBUG

server:
  port: ${SERVER_PORT:9999}

myapp:
  mongodb:
    username: ${USERNAME}
    password: ${PASSWORD}
    database: ${DATABASE}

---
spring:
  profiles:
    active: dev
  data:
    mongodb:
      uri: mongodb://${USER}:${PASSWORD}@localhost:27017/${DATABASE}
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=100,expireAfterAccess=5m # d, h, m, s, ms


# maximumSize=[integer]:   Максимальна кількість елементів у кеші.Після досягнення цієї межі застосовуватиметься
#                          політика витіснення для створення місця для нових елементів.
#
#
# expireAfterAccess=[duration]: Час життя елемента після останнього доступу до нього, після якого елемент буде
#                                автоматично видалено з кешу. Приклад: expireAfterAccess=5m (5 хвилин).
#
# maximumWeight=[integer]: Максимальна вага елементів у кеші, що використовується у поєднанні з weigher
#                          для визначення ваги кожного елемента. Потрібна явна вказівка вагової функції
#                          при налаштуванні кеша в коді.
#
# expireAfterWrite=[duration]: Час життя елемента після його додавання або останнього оновлення,
#                              після якого елемент буде автоматично видалено з кешу.
#
# weakKeys: Слабкі посилання для ключів кешу. Дозволяє збирачеві сміття видаляти ключі,
#           на які більше немає сильних посилань.
#
# softValues: Використання м'яких посилань для значень кешу. Значення можуть бути видалені збирачем сміття
#             за умов нестачі пам'яті.
#
# weakValues: Використання слабких посилань для значень кешу. Значення можуть бути видалені збирачем сміття,
#             якщо на них немає інших посилань.
#
# recordStats: Увімкнення збору статистики по роботі кешу, що дозволяє відстежувати показники ефективності кешу,
#              такі як кількість попадань та промахів.