logging:
  level:
    org:
      springframework.security: DEBUG

server:
  port: ${SERVER_PORT:9999}

---
spring:
  profiles:
    active: dev
  data:
    mongodb:
      uri: mongodb://${USER}:${PASSWORD}@localhost:27017/stat
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis
